=== elRohit/Project0_GestioHospital/BLOC DE PROGRAMACIÓ/visitesIRA.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="dateTimeOrNone">
    <xs:union memberTypes="xs:dateTime">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="None"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  <xs:simpleType name="dniType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{8}[A-Za-z]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="recetaType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Si"/>
    <xs:enumeration value="No"/>
  </xs:restriction>
</xs:simpleType>
  <xs:element name="visitas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="visita" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="numero_diagnostico" type="xs:integer"/>
              <xs:element name="dni_medico" type="dniType"/>
              <xs:element name="nombre_medico" type="xs:string"/>
              <xs:element name="apellidos_medico" type="xs:string"/>
              <xs:element name="tarjeta_sanitaria_paciente" type="xs:string"/>
              <xs:element name="nombre_paciente" type="xs:string"/>
              <xs:element name="apellidos_paciente" type="xs:string"/>
              <xs:element name="fecha_entrada" type="xs:dateTime"/>
              <xs:element name="fecha_salida" type="dateTimeOrNone"/>
              <xs:element name="tiene_receta" type="recetaType"/>
              <xs:element name="medicamentos" type="xs:string"/>
              <xs:element name="nombre_enfermedad" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== elRohit/Project0_GestioHospital/BLOC DE PROGRAMACIÓ/visites.xml
<?xml version='1.0' encoding='utf-8'?>
<visitas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="visitesIRA.xsd">
	<visita>
		<numero_diagnostico>0</numero_diagnostico>
		<dni_medico>12345678A</dni_medico>
		<nombre_medico>Juan</nombre_medico>
		<apellidos_medico>Garcia</apellidos_medico>
		<tarjeta_sanitaria_paciente>ADRIANALOPEZ24</tarjeta_sanitaria_paciente>
		<nombre_paciente>Adriana</nombre_paciente>
		<apellidos_paciente>López</apellidos_paciente>
		<fecha_entrada>2024-04-24T17:14:23</fecha_entrada>
		<fecha_salida>None</fecha_salida>
		<tiene_receta>Si</tiene_receta>
		<medicamentos>Paracetamol</medicamentos>
		<nombre_enfermedad>Gripe</nombre_enfermedad>
	</visita>
	<visita>
		<numero_diagnostico>1</numero_diagnostico>
		<dni_medico>12345678A</dni_medico>
		<nombre_medico>Juan</nombre_medico>
		<apellidos_medico>Garcia</apellidos_medico>
		<tarjeta_sanitaria_paciente>ADRIANALOPEZ24</tarjeta_sanitaria_paciente>
		<nombre_paciente>Adriana</nombre_paciente>
		<apellidos_paciente>López</apellidos_paciente>
		<fecha_entrada>2024-04-29T17:08:22</fecha_entrada>
		<fecha_salida>2024-04-29T17:08:22</fecha_salida>
		<tiene_receta>No</tiene_receta>
		<medicamentos>None</medicamentos>
		<nombre_enfermedad>None</nombre_enfermedad>
	</visita>
	<visita>
		<numero_diagnostico>2</numero_diagnostico>
		<dni_medico>12345678A</dni_medico>
		<nombre_medico>Juan</nombre_medico>
		<apellidos_medico>Garcia</apellidos_medico>
		<tarjeta_sanitaria_paciente>ADRIANALOPEZ24</tarjeta_sanitaria_paciente>
		<nombre_paciente>Adriana</nombre_paciente>
		<apellidos_paciente>López</apellidos_paciente>
		<fecha_entrada>2025-04-29T16:47:02</fecha_entrada>
		<fecha_salida>2025-04-29T17:47:02</fecha_salida>
		<tiene_receta>No</tiene_receta>
		<medicamentos>None</medicamentos>
		<nombre_enfermedad>None</nombre_enfermedad>
	</visita>
	<visita>
		<numero_diagnostico>3</numero_diagnostico>
		<dni_medico>12345678A</dni_medico>
		<nombre_medico>Juan</nombre_medico>
		<apellidos_medico>Garcia</apellidos_medico>
		<tarjeta_sanitaria_paciente>ADRIANALOPEZ24</tarjeta_sanitaria_paciente>
		<nombre_paciente>Adriana</nombre_paciente>
		<apellidos_paciente>López</apellidos_paciente>
		<fecha_entrada>2025-04-30T16:47:02</fecha_entrada>
		<fecha_salida>None</fecha_salida>
		<tiene_receta>Si</tiene_receta>
		<medicamentos>Paracetamol</medicamentos>
		<nombre_enfermedad>Gripe</nombre_enfermedad>
	</visita>
	<visita>
		<numero_diagnostico>4</numero_diagnostico>
		<dni_medico>12345678A</dni_medico>
		<nombre_medico>Juan</nombre_medico>
		<apellidos_medico>Garcia</apellidos_medico>
		<tarjeta_sanitaria_paciente>ADRIANALOPEZ24</tarjeta_sanitaria_paciente>
		<nombre_paciente>Adriana</nombre_paciente>
		<apellidos_paciente>López</apellidos_paciente>
		<fecha_entrada>2025-04-30T16:47:02</fecha_entrada>
		<fecha_salida>None</fecha_salida>
		<tiene_receta>Si</tiene_receta>
		<medicamentos>Paracetamol</medicamentos>
		<nombre_enfermedad>Gripe</nombre_enfermedad>
	</visita>
</visitas>
